# Generated by Django 4.2.7 on 2026-04-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_order_orderitem_wishlist_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
