# Generated by Django 4.2.13 on 2026-04-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_genericmedicine_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='genericmedicine',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='generic_medicines/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='products/'),
        ),
    ]
